main: ca.loellenrobotics.mc.smp.SMPPlugin
name: LEPSS-SMP
authors: [LEP EDIT]
version: 1.1.0
api-version: 1.17
description: SMP Plugin for LEPSS.
commands:
   message:
      description: Message another player.
      aliases: [msg, tell, whisper, w, pm]
   reply:
      description: Send a reply to the last person messaged.
      aliases: [r]
   me:
      description: Describe an action.
   name:
      description: Set your real-life name.
   grade:
      description: Set your grade.
   school:
      description: Set your school (non-LEP students).
   colour:
      description: Set the colour of your name.
      aliases: [color]
